# Generated by Django 5.0 on 2026-05-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=100)),
                ('object_image', models.ImageField(upload_to='objects/')),
                ('confidence', models.FloatField(default=0)),
                ('detected_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
